# Generated by Django 3.0.5 on 2021-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qimage',
            field=models.ImageField(blank=True, null=True, upload_to='ques'),
        ),
    ]
