# Generated by Django 3.0.5 on 2021-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_qimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qimage',
            field=models.ImageField(blank=True, null=True, upload_to='mimages/ques'),
        ),
    ]
